version: '3.2'

services:
  javadochub:
    build: .
    expose:
      - '8086'
    volumes:
      - type: volume
        source: storage
        target: /home/user/.javadochub
        volume:
          nocopy: true
volumes:
  storage:
