= 自部署

== fat jar

* JDK 1.8
* 下载 https://github.com/DocsAggregationTools/javadochub/releases[JavadocHub-linux.tar.gz]
* 解压、启动服务
+
[source,bash]
....
tar -xzvf JavadocHub-linux.tar.gz
cd JavadocHub

# 根据情况修改 application.yaml
vi application.yaml

# 启动服务
sh start.sh

# 停止服务
sh stop.sh
....

+
.application.yaml
[source,yaml]
....
javadochub:
  maven:
    # maven 公共仓库，必填，默认 https://repo.maven.apache.org/maven2
    repository: https://repo.maven.apache.org/maven2
    # maven 私有仓库，选填
    internal:
    # 私有仓库私有包 group 前缀，私有仓库已填则必填，多个使用逗号分割，例如 world.weibiansanjue,com.weibiansanjue
    internal-group-prefix:
  # javadoc 存储路径
  storage: ${user.home}/.javadochub
....


== docker

.docker cli
[source,shell]
....
docker run -d -p 8086:8086 \
  -v javadochub-store:/root/.javadochub \
  --name javadochub \
  -e javadochub.maven.repository="https://repo.maven.apache.org/maven2" \  # <1>
#  -e javadochub.maven.internal="" \  # <2>
#  -e javadochub.maven.internal-group-prefix="" \  # <3>
  javadochub:0.1.3
....
<1> maven 公共仓库，必填，默认 https://repo.maven.apache.org/maven2
<2> maven 私有仓库，选填
<3> 私有仓库私有包 group 前缀，私有仓库已填则必填，多个使用逗号分割，例如 world.weibiansanjue,com.weibiansanjue

== docker-compose

.docker-compose.yml
[source,yaml]
....
include::example$docker-compose.yml[]
....

== 自编译

环境信息

* JDK 1.8
* maven 3

代码

[source,bash]
....
git clone https://github.com/DocsAggregationTools/javadochub.git
cd javadochub
....

编译

[source,bash]
....
mvn clean package
....

启动

[source,bash]
....
java -jar target/javadochub.jar
....

访问

link:http://localhost:8086[^]
